version: '3.3'
services:
    web:
        restart: always
        build: .
        command: bash -c "gunicorn shorter_link.wsgi:application --bind 0.0.0.0:8000"
        volumes:
            - .:/var/www/
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            - db
    db:
        image: postgres:11
        environment:
            - POSTGRES_USER=postgres_user
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=postgres_db
