# Generated by Django 3.0.6 on 2020-05-20 00:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256, validators=[django.core.validators.URLValidator()])),
                ('url_hash', models.CharField(db_index=True, max_length=16, unique=True)),
                ('url_short', models.CharField(blank=True, max_length=256, null=True, validators=[django.core.validators.URLValidator()])),
                ('date_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
